AparrotServer/Controllers/ParrotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AparrotServer.Controllers
{
    public class ParrotController : Controller
    {
        //
        // GET: /Parrot/

        public ActionResult Index()
        {
            return View();
        }

    }
}

AparrotServer/Controllers/SpeakController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AparrotServer.Controllers
{
    public class SpeakController : Controller
    {
        //
        // GET: /Speak/

        public ActionResult Index(string t = "Hello, world")
        {
            var text = t;

            var parameters = "-a 20 \"" + text + "\"";

            Response.Headers.Add("ESpeak-parameters", parameters);

            using(var driver = new ESpeakDriver())
            {
                var result = driver.Run(parameters);

                return new FileContentResult(result, "audio/wav");
            }
        }
    }
}

AparrotServer/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace AparrotServer.Controllers
{
    public class StatusController : Controller
    {
        //
        // GET: /Status/

        public ActionResult Index()
        {
            return new ContentResult()
            {
                Content = "OK",
                ContentType = "text/plain",
                ContentEncoding = Encoding.UTF8
            };
        }

    }
}

AparrotServer/Views/Parrot/Index.cshtml
@model object

@{
    ViewBag.Title = "Parrot Talks";
}

<h2>Parrot Talks</h2>

<img src="@Url.Content("Content/parrot_text_mode.png")"/>

@using(var form = Html.BeginForm("Index", "Speak", FormMethod.Get))
{
    @Html.TextBox("t");
           
    <input type="button" class="parrot-submit" value="Speak" />
}

<script type="text/javascript">

    function GetSpeakUrl(text) {
        var result = @Html.Raw(Json.Encode(Url.Action("Index", "Speak")));
        result += "?t=" + encodeURIComponent(text);
        return result;
    }

    $("input.parrot-submit").click(function () {
        $("audio").remove();
        var newAudio = $("<audio class='parrotText' autoplay='true'>");
        newAudio.prop("src", GetSpeakUrl($("input#t").val()));
        $("body").append(newAudio);
    });
</script>

AparrotServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js" type="text/javascript"></script>
</head>

<body>
    @RenderBody()
</body>
</html>